/**
 * @file biffurcation.h
 * @brief Contains the functionality to generate a bifurcation diagram for the Roessler system.
 *
 * This file exposes an interface to generate bifurcation diagram points using the
 * rigorous mathematical operations provided by the CAPD library.
 */

#ifndef BIFFURCATION_H
#define BIFFURCATION_H

#include <string>

/**
 * @brief Parameters for generating a Roessler bifurcation diagram
 */
struct BiffurcationParams {
    double x0 = 0.0;
    double y0 = -5.0;
    double z0 = 0.1;
    double a = 0.2;
    double b = 0.2;
    double c_min = 2.0;
    double c_max = 6.0;
    int S = 100;
    int n = 200;
    std::string prefix = "biff";
};

/**
 * @brief Generates a Roessler bifurcation diagram and saves it to files
 *
 * This function iterates over a range of parameter 'c' values in [c_min, c_max].
 * For each 'c', it integrates the Roessler equations and computes the Poincare
 * map on the section y = 0. It discards S iterations, then records the
 * x-coordinate of the Poincare map for n subsequent iterations.
 * The outputs generated are:
 * 1. A .dat file with the trajectory points (c, x)
 * 2. A .gp file which is a script for gnuplot to render the image
 * 3. A .png file which is the gnuplot output (generated by invoking gnuplot on the script)
 *
 * @param params the parameters defining the bifurcation diagram configuration
 * @throws std::runtime_error on integration failure or file write error
 */
void generate_biffurcation_diagram(const BiffurcationParams& params);

#endif // BIFFURCATION_H
