/**
 * @file roessler.h
 * @brief Contains the functionality to simulate the Roessler system.
 *
 * The Roessler system is a system of three non-linear ordinary differential equations:
 * dx/dt = -y - z
 * dy/dt = x + a*y
 * dz/dt = b + z*(x - c)
 *
 * It exhibits chaotic dynamics for certain parameter values. This file exposes an
 * interface to generate trajectories of this system over time.
 */

#ifndef ROESSLER_H
#define ROESSLER_H

#include <string>
#include <vector>

namespace capd {
namespace dynsys {
    class DVector;
}
}

/**
 * @brief Parameters for generating a Roessler trajectory
 */
struct RoesslerParams {
    double x0 = 1.0;
    double y0 = 1.0;
    double z0 = 1.0;
    double S = 100.0;
    double T = 100.0;
    double a = 0.2;
    double b = 0.2;
    double c = 5.7;
    std::string prefix = "roessler";
};

/**
 * @brief Generates a Roessler trajectory and saves it to files
 *
 * This function integrates the Roessler equations starting from (x0, y0, z0)
 * over a "discard" time S, and then generates output data points over a time T.
 * It uses the rigorous mathematical operations provided by the CAPD library.
 * The outputs generated are:
 * 1. A .dat file with the trajectory points
 * 2. A .gp file which is a script for gnuplot to render the image
 * 3. A .png file which is the gnuplot output (generated by invoking gnuplot on the script)
 *
 * @param params the parameters defining the Roessler ODE and output configuration
 * @throws std::runtime_error on integration failure or file write error
 */
void generate_roessler_data(const RoesslerParams& params);

#endif // ROESSLER_H
